;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname racket_turtle_koordinaatisto_ja_peilaus_esimerkkiratkaisuja) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f () #f)))
(require 2htdp/image)
(require teachpacks/racket-turtle)

;; Tehtäväsarja 1
;; --------------
;; Tehtävä 1 a)
(define K (list (set-origin)
                (set-bg-grid 30 30 "green")
                (change-color "black")
                (change-pen-size 3)
                (mirror-x-on)
                (go-to 0 90)
                (go-to 30 90)
                (go-to 30 15)
                (go-to 60 90)
                (go-to 90 90)
                (go-to 55 0)))

(draw K)

;; Tehtävä 1 b)
(define NUOLI (list (set-origin)
                (set-bg-grid 30 30 "green")
                (change-color "black")
                (change-pen-size 3)
                (mirror-y-on)
                (go-to 30 0)
                (go-to 30 90)
                (go-to 60 90)
                (go-to 0 180)))

(draw NUOLI)

;; Tehtävä 1 c)
(define KEIHÄSKUVIO (list (set-origin)
                    (set-bg-grid 30 30 "green")
                    (change-color "black")
                    (change-pen-size 3)
                    (mirror-y-on)
                    (mirror-x-on)
                    (go-to 45 45)
                    (go-to 30 60)
                    (go-to 90 60)
                    (go-to 120 120)
                    (go-to 60 90)
                    (go-to 60 30)
                    (go-to 30 60)))
(draw KEIHÄSKUVIO)

;; Tehtäväsarja 2
;; --------------
;; Tehtävä 3 a)
(define NELIÖT (list (set-origin)
                    (set-bg-grid 30 30 "green")
                    (change-color "black")
                    (change-pen-size 3)
                    (mirror-y-on)
                    (pen-up)
                    (change-color "red")
                    (go-to 0 60)
                    (pen-down)
                    (go-to 60 60)
                    (go-to 60 -60)
                    (go-to 0 -60)
                    (change-color "blue")
                    (go-to 60 0)
                    (go-to 0 60)
                    (pen-up)
                    (go-to 0 30)
                    (pen-down)
                    (change-color "black")
                    (go-to 30 30)
                    (go-to 30 -30)
                    (go-to 0 -30)
                    (go-to 30 0)
                    (go-to 0 30)))

(draw NELIÖT)

 ;; Tehtävä 3 b)
(define TÄHTI (list (set-origin)
                    (set-bg-grid 30 30 "green")
                    (change-color "red")
                    (change-pen-size 3)
                    (mirror-y-on)
                    (pen-up)
                    (go-to 0 60)
                    (pen-down)
                    (go-to 60 120)
                    (go-to 30 30)
                    (go-to 120 60)
                    (go-to 60 0)
                    (change-color "blue")
                    (go-to 120 -60)
                    (go-to 30 -30)
                    (go-to 60 -120)
                    (go-to 0 -60)
                    (change-color "orange")
                    (go-to 30 -30)
                    (go-to 60 0)
                    (go-to 30 30)
                    (go-to 0 60)
                    ))

(draw TÄHTI)

 ;; Tehtävä 4 (omat nimikirjaimet)
(define TP (list (set-origin)
                    (set-bg-grid 30 30 "green")
                    (change-color "black")
                    (change-pen-size 3)
                    (mirror-y-on)
                    (mirror-x-on)
                    (pen-up)
                    (go-to 60 0)
                    (pen-down)
                    (go-to 60 120)
                    (go-to 0 120)
                    (go-to 120 120)
                    (pen-up)
                    (go-to 150 120)
                    (pen-down)
                    (go-to 210 120)
                    (go-to 210 60)
                    (go-to 150 60)
                    (go-to 150 120)
                    (go-to 150 0)
                    ))
(draw TP)

 